- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  ansible.builtin.package:
    name:
      - build-essential
      - cmake
      - pkg-config
      - libpthread-stubs0-dev
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  ansible.builtin.package:
    name:
      - lua5.1
      - unzip
      - libtool
      - libtool-bin
      - gettext
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  ansible.builtin.package:
    name:
      - curl
      - htop
      - lsof
      - i3
      - ccache
      - ninja-build
      - python3-pip
      - dconf-editor
      - nvidia-settings
      - pavucontrol
      - moreutils
      - clangd
  tags:
    - install
    - core

- name: Install Clang
  become: true
  apt:
    name: ["clang", "clang-11", "clang-12", "clangd", "clangd-10", "clangd-11", "clangd-12"]
  tags:
    - install
    - neovim
    - core
